import { z } from "zod";

const text = (min = 2, max = 200) => z.string().trim().min(min).max(max).transform((v) => v.replace(/[<>]/g, ""));
const optional = (max = 200) => z.string().trim().max(max).transform((v) => v.replace(/[<>]/g, "")).optional().default("");
export const personSchema = z.object({ full_name: text(3, 120), approximate_age: z.coerce.number().int().min(0).max(120).optional(), department: text(), municipality: text(), area: optional(), last_seen_place: optional(), last_contact_at: z.string().optional(), description: text(10, 600), reporter_name: text(2, 100), relationship: text(2, 80), phone: text(7, 30), show_phone: z.coerce.boolean().default(false), consent: z.literal("on"), website: z.string().max(0).optional(), idempotency_key: z.string().uuid() });
export const personUpdateSchema = z.object({ case_id: z.string().uuid(), kind: z.enum(["CONTACTO", "VISTA", "TERCERO", "LOCALIZADA", "DESACTUALIZADA", "OTRA"]), message: text(5, 500), occurred_at: z.string(), place: optional(), author_name: text(2, 100), phone: optional(30), sensitive: z.coerce.boolean().default(false), website: z.string().max(0).optional(), idempotency_key: z.string().uuid() });
export const pointSchema = z.object({ type: z.enum(["COLLECTION", "SHELTER"]), name: text(3, 140), department: text(), municipality: text(), area: optional(), address: text(4, 200), reference: optional(), schedule: optional(120), phone: optional(30), services: optional(400), items: optional(400), capacity: z.coerce.number().int().min(0).optional(), observations: optional(500), idempotency_key: z.string().uuid(), website: z.string().max(0).optional() });
export const aidSchema = z.object({ department: text(), municipality: text(), area: text(), reference: optional(), people_count: z.coerce.number().int().min(1).max(100000).optional(), description: text(10, 800), contact_name: text(2, 100), contact_phone: text(7, 30), urgency: z.enum(["MEDIA", "ALTA", "CRITICA"]), needs: z.array(z.string()).min(1), idempotency_key: z.string().uuid(), website: z.string().max(0).optional() });
export const pinSchema = z.object({ public_id: z.string().min(6).max(20), token: z.string().min(6).max(100), status: z.string().max(40), resource_type: z.enum(["PERSON", "POINT", "AID"]) });

export function formObject(form: FormData) { return Object.fromEntries(form.entries()); }
export function splitList(v: string) { return v.split(",").map((x) => x.trim()).filter(Boolean); }
