"use client";
import Image from "next/image";
import { useRef,useState,useSyncExternalStore } from "react";
import { Camera,ImagePlus,LoaderCircle,RefreshCw,Trash2 } from "lucide-react";
import { input,label } from "./form-kit";
import { MAX_IMAGE_BYTES } from "@/lib/media-validation";

type ResourceType="PERSON"|"POINT"|"AID";type Asset={position:number;url:string;width:number;height:number};
const maxByType:Record<ResourceType,number>={PERSON:1,POINT:3,AID:3};
function validSignature(bytes:Uint8Array){const jpeg=bytes[0]===0xff&&bytes[1]===0xd8&&bytes[2]===0xff;const png=bytes[0]===0x89&&bytes[1]===0x50&&bytes[2]===0x4e&&bytes[3]===0x47&&bytes[4]===0x0d&&bytes[5]===0x0a&&bytes[6]===0x1a&&bytes[7]===0x0a;const riff=new TextDecoder().decode(bytes.slice(0,4))==="RIFF",webp=new TextDecoder().decode(bytes.slice(8,12))==="WEBP";return jpeg||png||(riff&&webp)}
async function compress(file:File){if(file.size>12*1024*1024)throw new Error("La imagen original es demasiado grande.");const bytes=new Uint8Array(await file.slice(0,16).arrayBuffer());if(!validSignature(bytes))throw new Error("El archivo no es un JPG, PNG o WebP válido.");const bitmap=await createImageBitmap(file);const ratio=Math.min(1,1600/Math.max(bitmap.width,bitmap.height));const canvas=document.createElement("canvas");canvas.width=Math.max(1,Math.round(bitmap.width*ratio));canvas.height=Math.max(1,Math.round(bitmap.height*ratio));const context=canvas.getContext("2d");if(!context)throw new Error("No se pudo procesar la imagen.");context.drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();const blob=await new Promise<Blob|null>(resolve=>canvas.toBlob(resolve,"image/webp",.76));if(!blob)throw new Error("Tu navegador no pudo convertir la imagen.");if(blob.size>MAX_IMAGE_BYTES)throw new Error("La imagen sigue superando 3 MB después de comprimirla.");return new File([blob],"fotografia.webp",{type:"image/webp"})}

export function MediaManager({resourceType,publicId,initialToken=""}:{resourceType:ResourceType;publicId:string;initialToken?:string}){
 const[token,setToken]=useState(initialToken);const urlToken=useSyncExternalStore(()=>()=>{},()=>new URLSearchParams(location.search).get("token")??"",()=>"");const accessToken=token||urlToken;const[verified,setVerified]=useState(false);const[assets,setAssets]=useState<Asset[]>([]);const[consent,setConsent]=useState(false);const[preview,setPreview]=useState("");const[file,setFile]=useState<File|null>(null);const[position,setPosition]=useState(0);const[progress,setProgress]=useState(0);const[error,setError]=useState("");const[busy,setBusy]=useState(false);const inputRef=useRef<HTMLInputElement>(null);
 async function verify(value=accessToken){setToken(value);setBusy(true);setError("");try{const response=await fetch("/api/media/access",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({resourceType,publicId,token:value})});const data=await response.json();if(!response.ok)throw new Error(data.error);setAssets(data.assets);setVerified(true)}catch(e){setVerified(false);setError(e instanceof Error?e.message:"No se pudo validar el acceso")}finally{setBusy(false)}}
 async function choose(chosen:File){setError("");try{const output=await compress(chosen);if(preview)URL.revokeObjectURL(preview);setFile(output);setPreview(URL.createObjectURL(output));const free=[...Array(maxByType[resourceType]).keys()].find(i=>!assets.some(a=>a.position===i));setPosition(free??0)}catch(e){setFile(null);setPreview("");setError(e instanceof Error?e.message:"Imagen inválida")}}
 function upload(){if(!file||!consent)return;setBusy(true);setError("");setProgress(0);const form=new FormData();form.set("resourceType",resourceType);form.set("publicId",publicId);form.set("token",token);form.set("position",String(position));form.set("consent","true");form.set("file",file);const xhr=new XMLHttpRequest();xhr.open("POST","/api/media");xhr.upload.onprogress=e=>{if(e.lengthComputable)setProgress(Math.round(e.loaded/e.total*100))};xhr.onload=async()=>{setBusy(false);let data;try{data=JSON.parse(xhr.responseText)}catch{}if(xhr.status<200||xhr.status>=300){setError(data?.error??"No se pudo subir");return}setFile(null);setPreview("");setProgress(100);await verify()};xhr.onerror=()=>{setBusy(false);setError("Se perdió la conexión durante la subida. Inténtalo de nuevo.")};xhr.send(form)}
 async function remove(slot:number){if(!confirm("¿Eliminar esta fotografía definitivamente?"))return;setBusy(true);const response=await fetch("/api/media",{method:"DELETE",headers:{"content-type":"application/json"},body:JSON.stringify({resourceType,publicId,token,position:slot})});const data=await response.json();setBusy(false);if(!response.ok){setError(data.error);return}await verify()}
 if(!verified)return <section className="card"><h2 className="text-xl font-bold">Fotografías</h2><p className="muted">Valida el PIN o enlace privado para añadir o modificar fotografías.</p><label className={label}>PIN o token privado<input className={input} value={accessToken} onChange={e=>setToken(e.target.value)} type="password" autoComplete="off"/></label><button type="button" className="btn-secondary" disabled={busy||!accessToken} onClick={()=>verify()}>{busy?<LoaderCircle className="animate-spin"/>:null} Validar acceso</button>{error&&<p className="error">{error}</p>}</section>;
 return <section className="form-card"><div><h2 className="text-xl font-bold">Gestionar fotografías</h2><p className="muted mt-1 text-sm">{resourceType==="PERSON"?"Una fotografía principal.":"Hasta tres fotografías."} Solo tú puedes modificarlas.</p></div><div className="grid gap-3 sm:grid-cols-3">{assets.map(a=><article className="grid gap-2" key={a.position}><div className="relative aspect-[4/3] overflow-hidden rounded-xl"><Image src={a.url} alt="Fotografía publicada" fill className="object-cover" unoptimized/></div><div className="flex gap-2"><button type="button" className="btn-secondary flex-1 text-sm" onClick={()=>{setPosition(a.position);inputRef.current?.click()}}><RefreshCw size={16}/>Reemplazar</button><button type="button" aria-label="Eliminar fotografía" className="btn-secondary text-red-700" onClick={()=>remove(a.position)}><Trash2 size={17}/></button></div></article>)}</div>{assets.length<maxByType[resourceType]&&<button type="button" className="btn-secondary" onClick={()=>inputRef.current?.click()}><ImagePlus size={18}/> Añadir fotografía</button>}<input ref={inputRef} className="sr-only" type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>{const chosen=e.target.files?.[0];if(chosen)void choose(chosen);e.currentTarget.value=""}}/>{preview&&<div className="grid gap-3"><div className="relative aspect-[4/3] max-w-md overflow-hidden rounded-xl"><Image src={preview} alt="Previsualización antes de subir" fill className="object-cover" unoptimized/></div><p className="text-sm"><Camera className="mr-1 inline" size={16}/>La imagen fue comprimida a WebP antes de transferirse.</p><label className="flex items-start gap-3 rounded-xl bg-amber-50 p-3 text-sm"><input className="mt-1 size-5" type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/><span><b>Confirmo que tengo autorización para publicar esta fotografía.</b><br/>No contiene documentos, historias clínicas, imágenes explícitas de personas heridas o fallecidas.</span></label><button type="button" className="btn-primary" disabled={!consent||busy} onClick={upload}>{busy?<LoaderCircle className="animate-spin"/>:<Camera size={18}/>} Subir fotografía</button>{busy&&<div><div className="h-2 overflow-hidden rounded-full bg-slate-200"><div className="h-full bg-teal-700 transition-all" style={{width:`${progress}%`}}/></div><p className="mt-1 text-sm">Subiendo: {progress}%</p></div>}</div>}{error&&<p className="error">{error}</p>}</section>
}
